{% set name = "pytest-instafail" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 33a606f7e0c8e646dc3bfee0d5e3a4b7b78ef7c36168cfa1f3d93af7ca706c9e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pytest >=2.9

test:
  imports:
    - pytest_instafail

about:
  home: https://github.com/pytest-dev/pytest-instafail
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'py.test plugin to show failures instantly '
  description: |
    pytest-instafail is a plugin for py.test that shows failures and errors
    instantly instead of waiting until the end of test session.
  doc_url: https://github.com/pytest-dev/pytest-instafail
  dev_url: https://github.com/pytest-dev/pytest-instafail

extra:
  recipe-maintainers:
    - asford
